### All Events

GET {{BASE_URL}}/events?include=user,attendees,attendees.user HTTP/1.1
Content-Type: application/json

# >>! /tmp/response.json


### Single Event

GET {{BASE_URL}}/events/2
Content-Type: application/json
Accept: application/json


### Create Event

POST {{BASE_URL}}/events?include=user,attendees HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "end_time": "2024-07-04 12:00:00",
  "name": "New Event",
  "start_time": "2024-07-01 10:00:00"
}


### Update Event

PUT {{BASE_URL}}/events/79
Content-Type: application/json

{
  "name": "Updated Event Name 1"
}


### ⚠ Delete Event

DELETE {{BASE_URL}}/events/2


### Attendees

GET {{BASE_URL}}/events/79/attendees
Accept: application/json


### Attendee

GET {{BASE_URL}}/events/79/attendees/50?include=user
Accept: application/json


### Add Attendee

GET {{BASE_URL}}/events/2/attendees
Accept: application/json


### ⚠ Remove Attendee

DELETE {{BASE_URL}}/events/2/attendees/1985
Accept: application/json


### Add Attendee to Event

POST {{BASE_URL}}/events/2/attendees
Content-Type: application/json


### 🔑 LOGIN

POST {{BASE_URL}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "kieran00@example.net",
    "password": "password"
}
