### All Events

GET {{BASE_URL}}/events?include=user,attendees,attendees.user HTTP/1.1
Content-Type: application/json

>>! /tmp/response.json


### Single Event

GET {{BASE_URL}}/events/2 HTTP/1.1
Accept: application/json


### Create Event

POST {{BASE_URL}}/events HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "end_time": "2024-07-04 12:00:00",
  "name": "New Event",
  "start_time": "2024-07-01 10:00:00"
}


### Update Event

PUT {{BASE_URL}}/events/1 HTTP/1.1
Content-Type: application/json

{
  "name": "Updated Event Name 1"
}


### Delete Event

DELETE {{BASE_URL}}/events/1 HTTP/1.1


### Attendees

GET {{BASE_URL}}/events/2/attendees HTTP/1.1
Accept: application/json


### Add Attendee

GET {{BASE_URL}}/events/2/attendees/1820 HTTP/1.1
Accept: application/json


### Remove Attendee

DELETE {{BASE_URL}}/events/2/attendees/1820 HTTP/1.1
Accept: application/json


### Add Attendee to Event

POST {{BASE_URL}}/events/2/attendees HTTP/1.1
Content-Type: application/json
